### PR TITLE
Added FN.IMPORT

### PR DESCRIPTION
**Pull request by humpity**
Imports referenced 'main' vars (only) to local vars inside current function.

### CODE REVIEW

**Comment by sraffens** [comment]
Imports **by referenced** 'main' vars (only) to local vars inside the current function.
FN.IMPORT.REFERENCE

Imports **by value** 'main' vars (only) to local vars inside the current function.
FN.IMPORT.VALUE

**Comment by jMarcS** [comment]
My apologies for neglecting this so long.

First let me say this is really nice work. Thank you for the time and effort it took to work this through.

Before making the pull, I have a couple of comments.

In `executeFN_IMPORT()` you have these lines commented:
```
// *Not Working:   gVar = searchVar(mGlobalSymbolTable, var);	// search global symbols
// *Not preferred: for (Var.Table symbols : mSymbolTables)	// search all namespaces (from 0?)
```
For the first one, `mGlobalSymbolTable` is a place-holder. If I'd ever gotten around to putting in global variables, that's where I would have put them. As it is, the table exists but it is always empty.

For the second, you've run into an old problem. When I first put in multiple symbol tables, I preserved the old behavior: a variable search starts at main and works its way inward through the call stack. If the same variable name exists in multiple contexts, BASIC! finds the _outermost_. I really think that's a mistake. Compilers, like C or Java, search from the inside outward. BASIC! could do that, too: just search the `mSymbolTables` stack backwards. (Yes, `for (Var.Table symbols : mSymbolTables)` does search from 0; you'd have to use a conventional `for` loop, not a `foreach`, to search backwards.)

- Do you think it would be better to search only the main variable table, as you do now, or to search inside-out as a "normal" compiler would?
- Would there be value in supporting both options? This would not be necessary if there were actually a global symbol table, but right now there is not. For instance, there could be `FN.IMPORT` to search all tables and `FN.IMPORT.MAIN` to import only the outermost.
- There are still some problems with the symbol tables when operating in an interrupt service routine (event handler). I don't think  your implementation of `FN.IMPORT` is affected, and I think that's the way it should be. Have you given this any thought?

Thanks.

**Comment by humpity** [comment]
Hi jMarc,

I really didn't think you would respond so quickly, there's no rush.
And there's no reason to do the actual pull so long as you can make use
of the code.

Yes, I'm familiar with the search options and I guessed about the place-holder.

It was difficult to predict what the current user base (few that they are)
preferences were, so I went with the 'main only' approach for minimal impact
since the outside-in OUTIN search could produce hard-to-debug errors.

The inside-out INOUT traditional search is a classic choice but it
hinders users wanting a 'global' if it hit a variable somewhere in a nested
function above your function, before it got to main. Again hard to debug, and it wasn't addressing
'the quest' for easy access to global values such as e.g the screen width.

So, yes FN.IMPORT.MAIN is what this request is about, and perhaps
FN.IMPORT.INOUT for the future of which I hear few users actually 
wanting INOUT specifically as it seems a fairly advanced sort of programming.

Also, FN.IMPORT.MAIN seems long winded, so maybe FN.IMPORT should default
to MAIN and reserve FN.IMPORT.INOUT and FN.IMPORT.OUTIN for the future?


And what about that comment from sraffens? Import by value or reference?
Seems like a logical request. But adds to the complexity and verboseness.
The user could probably get by without 'by value' if he is careful. Or would
FN.IMPORT &var1,var2 be better an quicker ? I think we should keep things
simple for now.

And now for some notes that are not related but I need to get off my chest;
About Interrupts.
A)I also wanted to restrict the variable search within an Interrupt, so
that it would not do the OUTIN search but MAIN only. Again, easier to debug.

B)As aFox pointed out, if the interrupt code calls a function, then that
function gets restricted to the same scope as the interrupt code (because
it's still in an interrupt). 
At first, I thought the solution was a to simply test if the code was inside
a function, but this doesn't work, because the interrupt itself might have
occured inside a function, and this would overide the main block of the
interrupt code.

So far, I've come to the conclusion that when a variable lookup occurs,
then it must know a) whether it is in the main block of an interrupt,
and b) if we are both in an interrupt and a function, then determine wether
the function was called from the interrupt.
I've been thinking on an off for months, of a 'clever' flag that resets
whenever an interrupt occurs and increments when a function is called.
But never got around to trying it out. There is always something nagging
me at the back of my head that there's something wrong about it.

**Comment by olimaticer** [comment]
Hi Marc

> Do you think it would be better to search only the main variable table, as you do now, or to search inside-out as a "normal" compiler would?

Yes, it is different. But do we have trouble with it? Where is the advantage?
Marc, I remember, we talked about overwriting Basic! functions with self implemented ones months ago. Could this be a reason for the search direction? It is just a thought.

> Would there be value in supporting both options? This would not be necessary if there were actually a global symbol table, but right now there is not. For instance, there could be FN.IMPORT to search all tables and FN.IMPORT.MAIN to import only the outermost.


Does it make sense? Or is it just complexity?
I vote only for the outermost, because the most useres get in trouble using INCLUDE maybe for the Gwlib or others.
Or is your suggestion like the opportunities in Java to cross reference variables back and forth the classes. 
FN.IMPORT <mVar_var>, <from_function_func> 
Function A imports from function B and B imports from A. 
Can be done, but does not have to be. 
Ahh, I remember, you are not a friend of compressed HashMaps, also called Bundles or in VisualBasic Dictionaries (uncompressed) . ;)


> There are still some problems with the symbol tables when operating in an interrupt service routine (event handler). I don't think your implementation of FN.IMPORT is affected, and I think that's the way it should be. Have you given this any thought?

I closed this interrupt service routine backdoor and added Globas.all and Globas.none mainly for legacy reasons. I have implemented Humpty's suggestion as Globals.fnimp also. To date, I saw no unwanted side effects.

```
	// Always returns a Var, never null. Can use this Var anywhere;
	// if it was one of the "working Var" pool from parseVar() it gets copied.
	private Var searchVar(Var var) {				// search for a variable by name
// Skip global table for now, there's nothing in it.
		Var v = null;				
//		Var v = searchVar(mGlobalSymbolTable, var);	// first search global symbols
//		if (v == null) {
		/*
		if (interruptResume < 0) {				// normal operation, not in interrupt
			if (interruptResume < 0) {				// normal operation, not in interrupt
				v = searchVar(mSymbolTable, var);	// search local symbols
			} else {										// in interrupt
				for (Var.Table symbols : mSymbolTables) {	// search all tables
					v = searchVar(symbols, var);
					if (v != null) { break; }
				}
			}
		 */
		//Added !mLocals to prevent function leaks at Interruption // vv2017-02-13gt
		//Added mGlobals to enable global values // 2017-02-18gt
		//PrintShow("mFuncOpenCounter " + mFuncOpenCounter);
		if ( mGlobals && !mLocals ) {				// Globals = true and Locals = false //2017-02-27gt
			for (Var.Table symbols : mSymbolTables) {	// search all tables
				v = searchVar(symbols, var);
				if (v != null) { break; }
			}
		} else {										
			v = searchVar(mSymbolTable, var);	// search local symbols
		} // ^^2017-02-13gt
		//vv2017-07-20gt
		//Can be combined with the if statement above after intensive tests.
		if (interruptResume >= 0 && !( mGlobals && !mLocals )) {
			if (mFuncOpenCounter <= mCurrentFuncLevel.peek()){
				//int zz = -1;
				for (Var.Table symbols : mSymbolTables) {	// search all tables
					//++zz ;
					v = searchVar(symbols, var);
					if (v != null) { 
						//PrintShow("zz = " + zz + "   var from SymTable "+ v);
						break;
					}
				}
			}
		}//^^2017-07-20gt
		if (v != null)		{ return v; }
//		}
		return var.copy();							// not in lists of variable names, return new Var
	}

```
Gregor

**Comment by humpity** [comment]
Just an update here "About Interrupts";
You can forget about the ramble I had trying to solve the scope problem in an interrupt, I finally
dropped the clever flag system and just used a simple scope flag for variable lookup.
The flag is saved/restored at keypoints in Run.java, namely during function calls, function exits,
interrupt servicing and interrupt resume.
In my new code, there are only two places where 'main' scope (and 'only' main) is searched;
a) In the main program block
b) In the main block of an interrupt.
c) In fn.import
Any where else, it's local only, (i.e all functions whether in an interrupt or not or called from.)
I probably won't be making anymore pull requests, but raise issues instead.

**Comment by humpity** [comment]
Closing pull request , as new issues look muddled with github.

**Pull request closed without merging**
